// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ProjectTrackingContext))]
    [Migration("20260601151835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CityName = "Dakar",
                            CountryID = 1,
                            RegionName = "Dakar Region"
                        },
                        new
                        {
                            CityID = 2,
                            CityName = "Thiès",
                            CountryID = 1,
                            RegionName = "Thiès Region"
                        },
                        new
                        {
                            CityID = 3,
                            CityName = "Saint-Louis",
                            CountryID = 1,
                            RegionName = "Saint-Louis"
                        },
                        new
                        {
                            CityID = 4,
                            CityName = "Freetown",
                            CountryID = 2,
                            RegionName = "Western Area"
                        },
                        new
                        {
                            CityID = 5,
                            CityName = "Bo",
                            CountryID = 2,
                            RegionName = "Southern Province"
                        },
                        new
                        {
                            CityID = 6,
                            CityName = "Monrovia",
                            CountryID = 3,
                            RegionName = "Montserrado"
                        });
                });

            modelBuilder.Entity("Backend.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryID");

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = 1,
                            CountryCode = "SN",
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryID = 2,
                            CountryCode = "SL",
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryID = 3,
                            CountryCode = "LR",
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryID = 4,
                            CountryCode = "GN",
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryID = 5,
                            CountryCode = "MG",
                            CountryName = "Madagascar"
                        });
                });

            modelBuilder.Entity("Backend.Models.DmsInfrastructureOutput", b =>
                {
                    b.Property<int>("DmsInfrastructureOutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DmsInfrastructureOutputID"));

                    b.Property<string>("AdultChild")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("OutputAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OutputTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ProgramTypeOfOutput")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectIDNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SpecificOutputTypeID")
                        .HasColumnType("int");

                    b.HasKey("DmsInfrastructureOutputID");

                    b.HasIndex("OutputTypeID");

                    b.HasIndex("ProjectIDNumber");

                    b.HasIndex("SpecificOutputTypeID");

                    b.ToTable("DmsInfrastructureOutputs");
                });

            modelBuilder.Entity("Backend.Models.FinanceCode", b =>
                {
                    b.Property<int>("FinanceCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceCodeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FinanceCodeID");

                    b.ToTable("FinanceCodes");

                    b.HasData(
                        new
                        {
                            FinanceCodeID = 1,
                            Code = "LOC-SEN-DKR",
                            CodeType = "Location",
                            Description = "Dakar, Senegal location"
                        },
                        new
                        {
                            FinanceCodeID = 2,
                            Code = "LOC-SLE-FNA",
                            CodeType = "Location",
                            Description = "Freetown, Sierra Leone location"
                        },
                        new
                        {
                            FinanceCodeID = 3,
                            Code = "LOC-LBR-MNR",
                            CodeType = "Location",
                            Description = "Monrovia, Liberia location"
                        },
                        new
                        {
                            FinanceCodeID = 4,
                            Code = "PGM-EYE-CARE",
                            CodeType = "Program",
                            Description = "Ophthalmic program line"
                        },
                        new
                        {
                            FinanceCodeID = 5,
                            Code = "PGM-MCB-TRN",
                            CodeType = "Program",
                            Description = "Medical capacity building line"
                        },
                        new
                        {
                            FinanceCodeID = 6,
                            Code = "PGM-GEN-SURG",
                            CodeType = "Program",
                            Description = "General surgery program line"
                        },
                        new
                        {
                            FinanceCodeID = 7,
                            Code = "PUR-TRN-NURS",
                            CodeType = "Purpose",
                            Description = "Nurse clinical mentoring purpose"
                        },
                        new
                        {
                            FinanceCodeID = 8,
                            Code = "PUR-OPS-SURG",
                            CodeType = "Purpose",
                            Description = "Direct surgical operations purpose"
                        });
                });

            modelBuilder.Entity("Backend.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionID"));

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitutionID");

                    b.HasIndex("CountryID");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            InstitutionID = 1,
                            CountryID = 1,
                            InstitutionName = "Hôpital Principal de Dakar"
                        },
                        new
                        {
                            InstitutionID = 2,
                            CountryID = 1,
                            InstitutionName = "Thiès Regional Hospital"
                        },
                        new
                        {
                            InstitutionID = 3,
                            CountryID = 2,
                            InstitutionName = "Connaught Hospital Freetown"
                        },
                        new
                        {
                            InstitutionID = 4,
                            CountryID = 3,
                            InstitutionName = "JFK Medical Center Monrovia"
                        });
                });

            modelBuilder.Entity("Backend.Models.OutputType", b =>
                {
                    b.Property<int>("OutputTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutputTypeID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OutputTypeID");

                    b.ToTable("OutputTypes");

                    b.HasData(
                        new
                        {
                            OutputTypeID = 1,
                            Category = "Participant",
                            TypeName = "Participants Trained"
                        },
                        new
                        {
                            OutputTypeID = 2,
                            Category = "Participant",
                            TypeName = "Instruction Days Delivered"
                        },
                        new
                        {
                            OutputTypeID = 3,
                            Category = "Participant",
                            TypeName = "Mentorship Hours Completed"
                        },
                        new
                        {
                            OutputTypeID = 4,
                            Category = "Patient",
                            TypeName = "Surgeries Performed"
                        },
                        new
                        {
                            OutputTypeID = 5,
                            Category = "Patient",
                            TypeName = "Patients Screened"
                        },
                        new
                        {
                            OutputTypeID = 6,
                            Category = "Patient",
                            TypeName = "Dental Extractions"
                        },
                        new
                        {
                            OutputTypeID = 7,
                            Category = "Patient",
                            TypeName = "Anesthesia Cases Managed"
                        },
                        new
                        {
                            OutputTypeID = 8,
                            Category = "DMS",
                            TypeName = "Infrastructure Projects Completed"
                        },
                        new
                        {
                            OutputTypeID = 9,
                            Category = "DMS",
                            TypeName = "Equipment Donations Distributed"
                        },
                        new
                        {
                            OutputTypeID = 10,
                            Category = "DMS",
                            TypeName = "Advocacy Meetings Held"
                        });
                });

            modelBuilder.Entity("Backend.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantIDNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantIDNumber"));

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParticipantID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfessionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ParticipantIDNumber");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("ParticipantID")
                        .IsUnique()
                        .HasFilter("[ParticipantID] IS NOT NULL");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Backend.Models.ParticipantType", b =>
                {
                    b.Property<int>("ParticipantTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantTypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ParticipantTypeID");

                    b.ToTable("ParticipantTypes");

                    b.HasData(
                        new
                        {
                            ParticipantTypeID = 1,
                            TypeName = "Surgeon / Doctor"
                        },
                        new
                        {
                            ParticipantTypeID = 2,
                            TypeName = "Anesthetic Provider"
                        },
                        new
                        {
                            ParticipantTypeID = 3,
                            TypeName = "Registered Nurse"
                        },
                        new
                        {
                            ParticipantTypeID = 4,
                            TypeName = "Biomedical Technician"
                        },
                        new
                        {
                            ParticipantTypeID = 5,
                            TypeName = "Sterile Processing Staff"
                        },
                        new
                        {
                            ParticipantTypeID = 6,
                            TypeName = "Community Health Facilitator"
                        });
                });

            modelBuilder.Entity("Backend.Models.PatientOutput", b =>
                {
                    b.Property<int>("PatientOutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientOutputID"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<decimal>("OutputAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OutputTypeID")
                        .HasColumnType("int");

                    b.Property<string>("PatientID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjectIDNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatientOutputID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("OutputTypeID");

                    b.HasIndex("ProjectIDNumber");

                    b.ToTable("PatientOutputs");
                });

            modelBuilder.Entity("Backend.Models.PlannedOutput", b =>
                {
                    b.Property<int>("PlannedOutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlannedOutputID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlannedDateYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlannedOutputTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectIDNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReportingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlannedOutputID");

                    b.HasIndex("PlannedOutputTypeID");

                    b.HasIndex("ProjectIDNumber");

                    b.ToTable("PlannedOutputs");
                });

            modelBuilder.Entity("Backend.Models.ProgramName", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProgramID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgramNames");

                    b.HasData(
                        new
                        {
                            ProgramID = 1,
                            Description = "Cataract and other ophthalmic surgeries",
                            Name = "Ophthalmic (Eye) Surgery"
                        },
                        new
                        {
                            ProgramID = 2,
                            Description = "Reconstructive surgeries for facial deformities",
                            Name = "Maxillofacial Surgery"
                        },
                        new
                        {
                            ProgramID = 3,
                            Description = "Hernias, goiters, and pediatric specialized surgeries",
                            Name = "General & Pediatric Surgery"
                        },
                        new
                        {
                            ProgramID = 4,
                            Description = "Correction of clubfoot and pediatric orthopedic deformities",
                            Name = "Orthopedic (Clubfoot) Program"
                        },
                        new
                        {
                            ProgramID = 5,
                            Description = "Vesicovaginal fistula repairs and maternal training",
                            Name = "Women's Health / Fistula"
                        },
                        new
                        {
                            ProgramID = 6,
                            Description = "Free dental care and training of local students",
                            Name = "Dental & Oral Health"
                        },
                        new
                        {
                            ProgramID = 7,
                            Description = "Training local surgeons, nurses, and technicians",
                            Name = "Medical Capacity Building (MCB)"
                        });
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Property<int>("ProjectIDNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectIDNumber"));

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinanceLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("FinanceProgramID")
                        .HasColumnType("int");

                    b.Property<int?>("FinancePurposeID")
                        .HasColumnType("int");

                    b.Property<string>("FrenchProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InstructionDays")
                        .HasColumnType("int");

                    b.Property<string>("MasterStatsCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MasterStatsCategoryGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParticipantTypeID")
                        .HasColumnType("int");

                    b.Property<string>("PreShipPost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProjectTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("ShipID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectIDNumber");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("FinanceLocationID");

                    b.HasIndex("FinanceProgramID");

                    b.HasIndex("FinancePurposeID");

                    b.HasIndex("ParticipantTypeID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("ProjectID")
                        .IsUnique()
                        .HasFilter("[ProjectID] IS NOT NULL");

                    b.HasIndex("ProjectTypeID");

                    b.HasIndex("ShipID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Backend.Models.ProjectParticipantOutput", b =>
                {
                    b.Property<int>("ProjectParticipantOutputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectParticipantOutputID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutputAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OutputTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantIDNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectIDNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SpecificOutputTypeID")
                        .HasColumnType("int");

                    b.HasKey("ProjectParticipantOutputID");

                    b.HasIndex("OutputTypeID");

                    b.HasIndex("ParticipantIDNumber");

                    b.HasIndex("ProjectIDNumber");

                    b.HasIndex("SpecificOutputTypeID");

                    b.ToTable("ProjectParticipantOutputs");
                });

            modelBuilder.Entity("Backend.Models.ProjectType", b =>
                {
                    b.Property<int>("ProjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectTypeID");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            ProjectTypeID = 1,
                            TypeName = "Surgical Outreach"
                        },
                        new
                        {
                            ProjectTypeID = 2,
                            TypeName = "Clinical Training Course"
                        },
                        new
                        {
                            ProjectTypeID = 3,
                            TypeName = "Mentorship & Shadowing"
                        },
                        new
                        {
                            ProjectTypeID = 4,
                            TypeName = "Hospital Infrastructure Setup"
                        });
                });

            modelBuilder.Entity("Backend.Models.Ship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShipID");

                    b.HasIndex("ShipName")
                        .IsUnique();

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            ShipID = 1,
                            IsActive = true,
                            ShipName = "Global Mercy"
                        },
                        new
                        {
                            ShipID = 2,
                            IsActive = true,
                            ShipName = "Africa Mercy"
                        },
                        new
                        {
                            ShipID = 3,
                            IsActive = true,
                            ShipName = "None / Land-based"
                        });
                });

            modelBuilder.Entity("Backend.Models.SpecificOutputType", b =>
                {
                    b.Property<int>("SpecificOutputTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecificOutputTypeID"));

                    b.Property<int>("OutputTypeID")
                        .HasColumnType("int");

                    b.Property<string>("SpecificTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SpecificOutputTypeID");

                    b.HasIndex("OutputTypeID");

                    b.ToTable("SpecificOutputTypes");

                    b.HasData(
                        new
                        {
                            SpecificOutputTypeID = 1,
                            OutputTypeID = 1,
                            SpecificTypeName = "Primary Surgical Training"
                        },
                        new
                        {
                            SpecificOutputTypeID = 2,
                            OutputTypeID = 1,
                            SpecificTypeName = "Safe Surgery checklist Training"
                        },
                        new
                        {
                            SpecificOutputTypeID = 3,
                            OutputTypeID = 4,
                            SpecificTypeName = "Cataract Surgery"
                        },
                        new
                        {
                            SpecificOutputTypeID = 4,
                            OutputTypeID = 4,
                            SpecificTypeName = "Cleft Lip Repair"
                        },
                        new
                        {
                            SpecificOutputTypeID = 5,
                            OutputTypeID = 4,
                            SpecificTypeName = "Fistula Repair"
                        },
                        new
                        {
                            SpecificOutputTypeID = 6,
                            OutputTypeID = 9,
                            SpecificTypeName = "Anesthesia Machine Donation"
                        },
                        new
                        {
                            SpecificOutputTypeID = 7,
                            OutputTypeID = 9,
                            SpecificTypeName = "Surgical Pack Donation"
                        });
                });

            modelBuilder.Entity("Backend.Models.City", b =>
                {
                    b.HasOne("Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Backend.Models.DmsInfrastructureOutput", b =>
                {
                    b.HasOne("Backend.Models.OutputType", "OutputType")
                        .WithMany()
                        .HasForeignKey("OutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("DmsInfrastructureOutputs")
                        .HasForeignKey("ProjectIDNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.SpecificOutputType", "SpecificOutputType")
                        .WithMany()
                        .HasForeignKey("SpecificOutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OutputType");

                    b.Navigation("Project");

                    b.Navigation("SpecificOutputType");
                });

            modelBuilder.Entity("Backend.Models.Institution", b =>
                {
                    b.HasOne("Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Backend.Models.Participant", b =>
                {
                    b.HasOne("Backend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Backend.Models.PatientOutput", b =>
                {
                    b.HasOne("Backend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.OutputType", "OutputType")
                        .WithMany()
                        .HasForeignKey("OutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("PatientOutputs")
                        .HasForeignKey("ProjectIDNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("OutputType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Models.PlannedOutput", b =>
                {
                    b.HasOne("Backend.Models.OutputType", "PlannedOutputType")
                        .WithMany()
                        .HasForeignKey("PlannedOutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("PlannedOutputs")
                        .HasForeignKey("ProjectIDNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlannedOutputType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.HasOne("Backend.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FinanceCode", "FinanceLocation")
                        .WithMany()
                        .HasForeignKey("FinanceLocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FinanceCode", "FinanceProgram")
                        .WithMany()
                        .HasForeignKey("FinanceProgramID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FinanceCode", "FinancePurpose")
                        .WithMany()
                        .HasForeignKey("FinancePurposeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.ParticipantType", "ParticipantType")
                        .WithMany()
                        .HasForeignKey("ParticipantTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.ProgramName", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("FinanceLocation");

                    b.Navigation("FinanceProgram");

                    b.Navigation("FinancePurpose");

                    b.Navigation("ParticipantType");

                    b.Navigation("Program");

                    b.Navigation("ProjectType");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Backend.Models.ProjectParticipantOutput", b =>
                {
                    b.HasOne("Backend.Models.OutputType", "OutputType")
                        .WithMany()
                        .HasForeignKey("OutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Participant", "Participant")
                        .WithMany("AttendedProjects")
                        .HasForeignKey("ParticipantIDNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("ParticipantOutputs")
                        .HasForeignKey("ProjectIDNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.SpecificOutputType", "SpecificOutputType")
                        .WithMany()
                        .HasForeignKey("SpecificOutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OutputType");

                    b.Navigation("Participant");

                    b.Navigation("Project");

                    b.Navigation("SpecificOutputType");
                });

            modelBuilder.Entity("Backend.Models.SpecificOutputType", b =>
                {
                    b.HasOne("Backend.Models.OutputType", "OutputType")
                        .WithMany()
                        .HasForeignKey("OutputTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutputType");
                });

            modelBuilder.Entity("Backend.Models.Participant", b =>
                {
                    b.Navigation("AttendedProjects");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Navigation("DmsInfrastructureOutputs");

                    b.Navigation("ParticipantOutputs");

                    b.Navigation("PatientOutputs");

                    b.Navigation("PlannedOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
